version: '3'

networks:
    db-line:
      external:
        name: db-line
        
services:
  nginx:
          # image: "php7-docker"
    build: .
    container_name: buuline-backend
    ports:
        - "8182:8882"
    networks:
        - db-line
    volumes:
        - /home/buuline/backend:/var/www/html
